---
# Configuration directives for Travis CI
# --------------------------------------

# [Travis CI] http://travis-ci.org
# [configuration] http://about.travis-ci.org/docs/user/build-configuration/
services: docker
sudo: required
env:
  - distro: ubuntu1804
    playbook: test.yml
  - distro: ubuntu1604
    playbook: test.yml
  - distro: debian9
    playbook: test.yml
  - distro: debian8
    playbook: test.yml

before_script:
  - sudo apt-get install openssh-client
  - ssh-keygen -b 2048 -t rsa -f ~/.ssh/id_rsa -q -N ""

script:
  # Configure test script so we can run extra tests after playbook is run.
  - export container_id=$(date +%s)
  - export cleanup=false
  - export exposed_port=22

  # Download test shim.
  - wget -O ${PWD}/tests/test.sh https://gist.githubusercontent.com/arnobirchler/627e4655465b696a0b521a560bc2206f/raw/
  - chmod +x ${PWD}/tests/test.sh

  # Run tests.
  - ${PWD}/tests/test.sh

  # Test SSH connection
  - export ipaddr=$(docker inspect --format '{{ .NetworkSettings.IPAddress }}' $container_id)
  - ssh -oStrictHostKeyChecking=no -t scott@$ipaddr "exit"

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/