---
# tasks file for ansible-role-create-account 
- name: APT | Update
  apt:
    upgrade: dist
    update_cache: yes
- name: "SSH | TARGET | install openssh-server"
  apt:
    name: openssh-server
    state: present
- name: "SSH | TARGET | add pub key to ({{ user }})"
  authorized_key:
    user: "{{ user }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
- name: "SSH | TARGET | add pub key to ({{ sudoer }})"
  authorized_key:
    user: "{{ sudoer }}"
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
    state: present
- name: "SSH | TARGET | start openssh-server"
  service:
    -name: ssh
    -state: restarted